AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CodePipeline for buildIT Wilpro exercise. Deploys a CodePipeline and CloudFormation Stacks.

Parameters:
  pGitHubRepoOwner:
    Type: String
    Description: Owner of the GitHub Repository
    Default: alexsunins

  pGitHubRepoName:
    Type: String
    Description: Name of the GitHub Repository
    Default: devops-test

  pGitHubBranch:
    Type: String
    Description: Name of branch to use inside the GitHub Repository
    Default: master
  
  pGitHubOAuthTokenSecret:
    Description: The name of a Secret that is holding GitHub OAuth token
    Type: String
    Default: '/wilpro/GithubTokenSecretArn'

  pTargetRegion:
    Description: Target region for Code Deploy
    Type: String
    Default: eu-west-2

Resources:
  # network components
  rVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  
  rInternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: rVPC

  rGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref rVPC
      InternetGatewayId: !Ref rInternetGateway
  
  rPublicSubnetA: # a subnet that is accessbile from the Internet
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]
  
  rPublicSubnetB: # a subnet that is accessbile from the Internet
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref rVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]

  rPublicRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rVPC

  rPublicRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rVPC

  rPublicRouteA:
    Type: AWS::EC2::Route
    DependsOn: rGatewayAttachment
    Properties:
      RouteTableId: !Ref rPublicRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rInternetGateway
  
  rPublicRouteB:
    Type: AWS::EC2::Route
    DependsOn: rGatewayAttachment
    Properties:
      RouteTableId: !Ref rPublicRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rInternetGateway
  
  rPublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref rPublicSubnetA
      RouteTableId: !Ref rPublicRouteTableA

  rPublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref rPublicSubnetB
      RouteTableId: !Ref rPublicRouteTableB
  
  # load balancer  
  rELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Port 80 Inbound'
      VpcId:
        Ref: rVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  rEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Port 80 Inbound'
      VpcId:
        Ref: rVPC
      SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            SourceSecurityGroupId:
              Ref: rELBSecurityGroup  
  
  rALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: rEC2TargetGroup
      LoadBalancerArn:
        Ref: rApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  rApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
      - Ref: rPublicSubnetA
      - Ref: rPublicSubnetB
      SecurityGroups:
      - Ref: rELBSecurityGroup
  
  rEC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: EC2TargetGroup
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: load_balancing.algorithm.type
        Value: 'round_robin'
      Targets:
      - Id:
          Ref: rAppServerOne
        Port: 80
      - Id:
          Ref: rAppServerTwo
        Port: 80
      UnhealthyThresholdCount: 3
      VpcId:
        Ref: rVPC

  # code pipeline
  rBuildArtifactS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pGitHubRepoName}-${pGitHubBranch}-pipeline

  rCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
                  - "s3:List*"
                Resource:
                  - !Sub 'arn:aws:s3:::${pGitHubRepoName}-${pGitHubBranch}-pipeline'
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                Resource:
                  - "arn:aws:s3:::codepipeline*"
                  - "arn:aws:s3:::elasticbeanstalk*"
              - Effect: Allow
                Action:
                  - "codecommit:CancelUploadArchive"
                  - "codecommit:GetBranch"
                  - "codecommit:GetCommit"
                  - "codecommit:GetUploadArchiveStatus"
                  - "codecommit:UploadArchive"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "elasticbeanstalk:*"
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "autoscaling:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "sns:*"
                  - "cloudformation:*"
                  - "rds:*"
                  - "sqs:*"
                  - "ecs:*"
                  - "iam:PassRole"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                  - "lambda:ListFunctions"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "opsworks:CreateDeployment"
                  - "opsworks:DescribeApps"
                  - "opsworks:DescribeCommands"
                  - "opsworks:DescribeDeployments"
                  - "opsworks:DescribeInstances"
                  - "opsworks:DescribeStacks"
                  - "opsworks:UpdateApp"
                  - "opsworks:UpdateStack"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:SetStackPolicy"
                  - "cloudformation:ValidateTemplate"
                  - "iam:PassRole"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: "*"

  rCodePipeline:
    DependsOn: rAppServerTwo
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-pipeline"
      ArtifactStore:
        Type: S3
        Location: !Ref rBuildArtifactS3Bucket
      RoleArn: !GetAtt rCodePipelineRole.Arn
      Stages:
        - Name: FetchSource
          Actions:
            - Name: Source-GitHub
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-source-artifacts"
              Configuration:
                Owner: !Ref pGitHubRepoOwner
                Repo: !Ref pGitHubRepoName
                Branch: !Ref pGitHubBranch
                OAuthToken: !Sub '{{resolve:secretsmanager:${pGitHubOAuthTokenSecret}:SecretString:GITHUB_ACCESS_TOKEN}}'
              RunOrder: 1
        - Name: Test
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-source-artifacts"
              OutputArtifacts:
                - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-test-output"
              Configuration:
                ProjectName: !Sub "${pGitHubRepoName}-${pGitHubBranch}-test"
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-source-artifacts"
              OutputArtifacts:
                - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-build-output"
              Configuration:
                ProjectName: !Sub "${pGitHubRepoName}-${pGitHubBranch}"
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              InputArtifacts:
              - Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-build-output"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Sub "${pGitHubRepoName}-application"
                DeploymentGroupName: !Sub "${pGitHubRepoName}-application"
              RunOrder: 1
  
  rCodePipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      AuthenticationConfiguration:
        SecretToken: !Sub '{{resolve:secretsmanager:${pGitHubOAuthTokenSecret}:SecretString:GITHUB_ACCESS_TOKEN}}'
      Filters:
      - JsonPath: '$.ref'
        MatchEquals: !Sub 'refs/heads/${pGitHubBranch}'
      Authentication: GITHUB_HMAC
      TargetPipeline: !Ref rCodePipeline
      TargetAction: Source-GitHub
      Name: !Sub '${pGitHubRepoName}-GitHub-Webhook'
      TargetPipelineVersion: !GetAtt rCodePipeline.Version
      RegisterWithThirdParty: true
  
  # code build
  rCodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - "arn:aws:logs:*:*:log-group:/aws/codebuild/*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                Resource: "arn:aws:s3:::codepipeline-*/*"
              - Sid: S3ListBuildArtifactBucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${pGitHubRepoName}-${pGitHubBranch}-pipeline'
              - Sid: S3ListGetPutObjectsBuildArtifactBucket
                Effect: Allow
                Action:
                  - s3:ListObjects
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub 'arn:aws:s3:::${pGitHubRepoName}-${pGitHubBranch}-pipeline/*'
                  
  
  rTestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-test"
      Description: CodeBuild project for running Node tests
      ServiceRole: !GetAtt rCodeBuildRole.Arn
      Artifacts:
        Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}-test"
        Type: CODEPIPELINE
        Packaging: NONE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.1
          phases:
            install:
              commands:
                - npm install
                - npm install -g mocha
            build:
              commands:
                - npm test
      TimeoutInMinutes: 10
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0-1.0.0
  
  rCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}"
      ServiceRole: !GetAtt rCodeBuildRole.Arn
      Artifacts:
        Name: !Sub "${pGitHubRepoName}-${pGitHubBranch}"
        Type: CODEPIPELINE
        Packaging: NONE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  # code deploy
  rDeployApplication:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: !Sub "${pGitHubRepoName}-application"

  rDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref rDeployApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: !Sub "${pGitHubRepoName}-application"
      Ec2TagFilters:
        - Key: name
          Value: !Sub "${pGitHubRepoName}-application"
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt rCodeDeployRole.Arn

  rCodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Sid: "1"
            Effect: Allow
            Principal:
              Service:
                - !Sub "codedeploy.${pTargetRegion}.amazonaws.com"
            Action: sts:AssumeRole
      Path: "/"
  
  rCodeDeployRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeDeployPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - ec2:Describe*
      Roles:
        - !Ref rCodeDeployRole
  
  # ec2 instances for code deploy
  rEC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: EC2DeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource: "*"

  rEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref rEC2InstanceRole
  
  rInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open ports 22 and 80
      VpcId:
        Ref: rVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  
  rEC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${pGitHubRepoName}-LaunchTemplate"
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt rEC2InstanceProfile.Arn
        ImageId: ami-1ec8d37a
        InstanceType: t2.nano
        # KeyName: MyKeyPair
        TagSpecifications:
          - ResourceType: instance
            Tags: 
              - Key: name
                Value: !Sub "${pGitHubRepoName}-application"              
        UserData:
          Fn::Base64: |
              #!/bin/bash -xe
              yum -y update
              yum install -y ruby
              yum install -y aws-cli
              curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
              sudo yum -y install nodejs
              cd /var
              mkdir nodeapp
              cd /home/ec2-user
              wget https://aws-codedeploy-eu-west-2.s3.amazonaws.com/latest/install
              chmod +x ./install
              ./install auto

  rAppServerOne:
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref rEC2LaunchTemplate
        Version: "1"
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: '0'
          GroupSet:
            - !GetAtt rInstanceSecurityGroup.GroupId
          SubnetId: !Ref rPublicSubnetA
  
  rAppServerTwo:
    DependsOn: rAppServerOne
    Type: 'AWS::EC2::Instance'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref rEC2LaunchTemplate
        Version: "1"
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: '0'
          GroupSet:
            - !GetAtt rInstanceSecurityGroup.GroupId
          SubnetId: !Ref rPublicSubnetB

  rGitHubAuthTokenSecret:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Sub '{{resolve:secretsmanager:${pGitHubOAuthTokenSecret}:SecretString:GITHUB_ACCESS_TOKEN}}'

Outputs:
  rALBDNS:
    Description: "Application Load Balancer Hostname"
    Value: !GetAtt rApplicationLoadBalancer.DNSName

  AppServerOne:
    Description: "App Server One"
    Value: !Ref rAppServerOne

  AppServerTwo:
    Description: "App Server Two"
    Value: !Ref rAppServerTwo

  CodePipeline:
    Description: "CodePipeline Access"
    Value: !Ref rCodePipeline
